apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tinybank-account-api
  description: Brian's Swagger PetStore Sample REST API
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  definition:
    $text: ./api/account-openapi-0.0.1.json