apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tinybank-account
  description: A sample microservice catalogued in Backstage.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: backstage/backstage
spec:
  type: service
  lifecycle: production
  owner: guests
  system: core-system
  providesApis:
    - tinybank-account-api
  consumesApis:
    - tinybank-customer-api
  dependsOn:
    - component: default/tinybank-customer